---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: db-password.txt
      - name: SOME_APIKEY
        valueFrom:
          secretKeyRef:
            name: my-secret
            key: some-apikey.txt
  restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    app: my-app
stringData:
  db-password.txt: "STRONG DEV DB PASSWORD"
  some-apikey.txt: "STRONG DEV SOME APIKEY"
